baseURL: https://rustyxlol.github.io/
languageCode: en-us
theme: PaperMod

title: Rusty

params:
    profileMode:
        enabled: true
        title: "Hi! I'm Rusty" # optional default will be site title
        subtitle: "97% introverted amateur programmer"
        imageUrl: "https://avatars.githubusercontent.com/u/27452933?v=4" # optional
        imageTitle: "GitHub Avatar" # optional
        imageWidth: 240 # custom size
        imageHeight: 240 # custom size

    
    socialIcons: # optional
      - name: "stackoverflow"
      - name: "twitter"
        url: "https://twitter.com/rustyxlol"
        url: "https://stackoverflow.com/users/16024991/rusty"
      - name: "github"
        url: "https://github.com/rustyxlol"
      - name: "email"
        url: "mailto:rustyxlol@pm.me"
      - name: "rss"
        url: "/posts/index.xml"

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10

    - identifier: posts
      name: Posts
      url: /posts/
      weight: 20

    - identifier: projects
      name: Projects
      url: /projects/
      weight: 20

taxonomies:
  series: series

copyright: "© 2022 Rusty"