baseURL: https://rustyxlol.github.io/
languageCode: en-us
theme: PaperMod

title: Rusty

params:
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    ShowBreadCrumbs: true
    editPost:
      URL: "https://github.com/rustyxlol/rustyxlol.github.io/tree/master/content"
      Text: "Suggest Changes" # edit text
      appendFilePath: true # to append file path to Edit link

    profileMode:
        enabled: true
        title: "Hi! I'm Rusty" # optional default will be site title
        subtitle: "97% introverted amateur programmer"
        imageUrl: "https://avatars.githubusercontent.com/u/27452933?v=4" # optional
        imageTitle: "GitHub Avatar" # optional
        imageWidth: 240 # custom size
        imageHeight: 240 # custom size

    
    socialIcons: # optional
      - name: "stackoverflow"
        url: "https://stackoverflow.com/users/16024991/rusty"
      - name: "twitter"
        url: "https://twitter.com/rustyxlol"
      - name: "github"
        url: "https://github.com/rustyxlol"
      - name: "email"
        url: "mailto:rustyxlol@pm.me"

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10

    - identifier: posts
      name: Posts
      url: /posts/
      weight: 20

    - identifier: projects
      name: Projects
      url: /projects/
      weight: 20

taxonomies:
  series: series
  tags: tags

copyright: "© 2022 Rusty"
