name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          
      - name: Update PaperMod submodule
        run: |
          echo "Updating PaperMod submodule to latest commit..."
          cd themes/PaperMod
          git checkout master
          git pull origin master
          cd ../..
          git add themes/PaperMod
          git commit -m "Update PaperMod to latest" || echo "No changes to commit"
          git log -1 --oneline  # shows last commit of PaperMod
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify --environment production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/
